version: 2
jobs:
  build:
    working_directory: /opt/repo
    machine: true
    steps:
      - checkout

      - run: 
          name: Check wget speed on VM
          command: |
            cat /etc/issue
            cat /etc/os-release
            pwd
            echo ${USER}
            wget https://download.tizen.org/snapshots/tizen/unified/latest/repos/standard/packages/armv7l/dotnet-build-tools-2.0.0-25.1.armv7l.rpm

      - run:
          name: Bring up docker container
          command: |
            docker run -t -d -w /opt/repo -v /home/circleci/project:/opt/repo:rw --privileged --network host --name gbs_test retzero/gbs_ubuntu16.04

      - run:
          name: Check wget speed inside container
          command: |
            docker exec gbs_test bash -lc "wget https://download.tizen.org/snapshots/tizen/unified/latest/repos/standard/packages/armv7l/dotnet-build-tools-2.0.0-25.1.armv7l.rpm"

      - run:
          name: Build with gbs
          command: |
            docker exec gbs_test bash -lc "gbs build -A armv7l"
